# Generated by Django 5.0.3 on 2024-03-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('pub_date', models.DateField(verbose_name='Fecha de publicación')),
                ('source', models.CharField(max_length=255, verbose_name='Fuente')),
                ('gender', models.CharField(max_length=255, verbose_name='Género')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Imagen')),
                ('ideological_stance', models.CharField(max_length=255, verbose_name='Postura ideológica')),
                ('descriptor', models.CharField(max_length=255, verbose_name='Descriptor')),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Autores')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Categoría')),
            ],
        ),
    ]
