# Generated by Django 5.0.3 on 2024-03-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Temáticas', 'verbose_name_plural': 'Temáticas'},
        ),
    ]
