# Generated by Django 5.0.3 on 2024-03-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(default='Español', max_length=255, verbose_name='Idioma'),
        ),
    ]
