# Generated by Django 5.0.3 on 2024-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Años de experiencia'),
        ),
    ]
